Merge Feature Branch into Development Branch
RamseyNjire/re_former pull request #1
Opened 2020-11-22 11:21 UTC by RamseyNjire

In this project I build Rails forms, first using raw HTML, and then using a variety of Rails helpers. Hope you love it!

2020-11-22 13:07 UTC, addod19 requested changes
## Require changs :recycle: :traffic_light: 

Hi @RamseyNjire, great job on this project :+1: Kindly address the comments below so we can approve the project :slightly_smiling_face: 

- Kindly fix the error below. This error came as a result of running `rails s` after running the bundle install and migration. As a result of this, I am not able to test the app. Let us kindly fix it :smile: 

[Optional]
- Kindly create a partial for user form and reuse in `new` and `edit` view
- Kindly create a form view to displays a list of the error messages (with #errors and full_messages usage)
- Validate the email format by using either a regular expression or a built-in URI method.

Once this is fixed, kindly submit another code review request :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](linkedin.com/in/daniel-larbi-addo/)

2020-11-22 13:07 UTC, addod19 commented on app/controllers/users_controller.rb
> +      redirect_to new_user_path
Kindly change `redirect_to new_user_path` to `redirect_to edit_user_path`

2020-11-23 07:19 UTC, RamseyNjire commented
Hey! I've made the change in the user controller.

2020-11-23 08:28 UTC, peterrobert requested changes
### CHANGES REQUIRED :recycle: 

HELLO @RamseyNjire  VERY NICE PROGRESS :clap: GREAT WORK IMPLEMENTING THE CHANGES AS REQUESTED. HOWEVER, THERE ARE A FEW CHANGES TO BE MADE KINDLY CHECK BELOW :arrow_down: 

- [ ] There seems to be a problem with webpack in your project kindly fix it :arrow_down: 
![Screenshot from 2020-11-23 11-23-46](https://user-images.githubusercontent.com/32361963/99941082-74954180-2d7e-11eb-84de-c8b54d2a0bea.png)

NB: I was unable to run your application. Kindly fix and submit for another review.

### you can reach me on slack @peterrobert

### HAPPY CODING :computer:

2020-11-23 08:28 UTC, peterrobert commented on app/controllers/users_controller.rb
> +
When the data is valid, You should navigate to the edit_path

2020-11-23 08:53 UTC, RamseyNjire commented
The webpacker issue has been solved. I have included an instruction in the 'Readme' file to run `bundle exec rails webpacker:install`, just to make sure webpacker creates the manifest file. Run this after running `bundle install` when you clone the repo locally and everything should be fine.

2020-11-23 09:06 UTC, rOluochKe approved these changes
Hello @RamseyNjire 
### You got it right :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

2020-11-23 09:47 UTC, RamseyNjire commented
Great, doing the merge! All good here.

2020-11-23 09:47 UTC, merged